'use client';  // Chỉ định đây là Client Component

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"; // Nhập Bootstrap 5
import global_style from "@/styles/globals.module.css"; // Nếu bạn có thêm CSS tùy chỉnh
import style_01 from "@/styles/style_01.module.css"; // Nếu bạn có thêm CSS tùy chỉnh

import { Provider } from 'react-redux';
import store from '../store'; // Đảm bảo đường dẫn đúng tới Redux store

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}> {/* Bao quanh toàn bộ ứng dụng với Redux Provider */}
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </Provider>
  );
}
