# Generated by Django 5.2 on 2025-04-14 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(blank=True, max_length=10, null=True)),
                ('xoa_sua', models.CharField(blank=True, max_length=10, null=True)),
                ('ma_hang', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_hang', models.TextField(blank=True, null=True)),
                ('dvt', models.CharField(blank=True, max_length=50, null=True)),
                ('sl_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('don_gia_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ma_kho_luu_tru', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
