# Generated by Django 5.2 on 2025-04-16 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIEW_INVENTORY_STANDARD_REPORT_BY_WAREHOUSE_CODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hang', models.CharField(max_length=50)),
                ('ten_hang', models.TextField()),
                ('dvt', models.CharField(max_length=50)),
                ('ma_kho_nhan', models.CharField(max_length=50)),
                ('so_luong_ton_dau_ky', models.DecimalField(decimal_places=2, max_digits=15)),
                ('don_gia_ton_dau_ky', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gia_tri_ton_dau_ky', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tong_so_luong_nhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('don_gia_nhap_kho_binh_quan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tong_gia_tri_nhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tong_so_luong_xuat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('don_gia_xuat_kho_binh_quan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tong_gia_tri_xuat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('so_luong_ton_kho', models.DecimalField(decimal_places=2, max_digits=15)),
                ('don_gia_ton_kho', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gia_tri_ton_kho', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'inventory.VIEW_INVENTORY_STANDARD_REPORT_BY_WAREHOUSE_CODE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TB_INVENTORY_CATEGORIES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_hang', models.CharField(max_length=50)),
                ('ten_hang', models.TextField()),
                ('dvt', models.CharField(max_length=50)),
                ('sl_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('don_gia_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ma_kho_luu_tru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventory.TB_INVENTORY_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TB_INVENTORY_STOCK_RECEIVED_ISSSUED_RETURNED',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('so_phieu', models.CharField(max_length=50)),
                ('phan_loai_nhap_xuat_hoan', models.CharField(max_length=50)),
                ('ma_doi_tuong', models.CharField(max_length=50)),
                ('ngay_tren_phieu', models.DateTimeField()),
                ('so_phieu_de_nghi', models.CharField(max_length=50)),
                ('thong_tin_them', models.TextField(blank=True, null=True)),
                ('stt_dong', models.IntegerField(blank=True, null=True)),
                ('ma_hang', models.CharField(max_length=50)),
                ('so_luong', models.DecimalField(decimal_places=2, max_digits=15)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ghi_chu_sp', models.TextField(blank=True, null=True)),
                ('ma_kho_nhan', models.CharField(max_length=50)),
                ('ma_kho_xuat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventory.TB_INVENTORY_STOCK_RECEIVED_ISSSUED_RETURNED',
                'managed': True,
            },
        ),
    ]
