# Generated by Django 5.2 on 2025-04-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb_inventory_categories',
            table='TB_INVENTORY_CATEGORIES',
        ),
        migrations.AlterModelTable(
            name='tb_inventory_stock_received_isssued_returned',
            table='TB_INVENTORY_STOCK_RECEIVED_ISSSUED_RETURNED',
        ),
    ]
