# Generated by Django 5.2 on 2025-04-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventorycategory',
            table='tb_inventory_categories',
        ),
    ]
