# Generated by Django 5.2 on 2025-06-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tb_inventory_categories',
            table='inventory"."TB_INVENTORY_CATEGORIES',
        ),
        migrations.AlterModelTable(
            name='tb_inventory_stock_received_isssued_returned',
            table='inventory"."TB_INVENTORY_STOCK_RECEIVED_ISSSUED_RETURNED',
        ),
        migrations.AlterModelTable(
            name='view_inventory_report_quantity',
            table='inventory"."VIEW_INVENTORY_REPORT_QUANTITY"',
        ),
    ]
