# Generated by Django 5.2 on 2025-06-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_CLIENT_CATEGORIES',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_khach_hang', models.CharField(max_length=50)),
                ('ten_khach_hang', models.TextField()),
                ('ma_phan_loai_01', models.CharField(max_length=50)),
                ('ma_phan_loai_02', models.CharField(max_length=50)),
                ('ma_phan_loai_03', models.CharField(max_length=50)),
                ('ma_phan_loai_04', models.CharField(max_length=50)),
                ('ma_phan_loai_05', models.CharField(max_length=50)),
                ('ma_phan_loai_06', models.CharField(max_length=50)),
                ('ma_phan_loai_07', models.CharField(max_length=50)),
                ('ma_phan_loai_08', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventory.TB_CLIENT_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TB_SUPPLIER_CATEGORIES',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_nha_cung_cap', models.CharField(max_length=50)),
                ('ten_nha_cung_cap', models.TextField()),
                ('ma_phan_loai_01', models.CharField(max_length=50)),
                ('ma_phan_loai_02', models.CharField(max_length=50)),
                ('ma_phan_loai_03', models.CharField(max_length=50)),
                ('ma_phan_loai_04', models.CharField(max_length=50)),
                ('ma_phan_loai_05', models.CharField(max_length=50)),
                ('ma_phan_loai_06', models.CharField(max_length=50)),
                ('ma_phan_loai_07', models.CharField(max_length=50)),
                ('ma_phan_loai_08', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventory.TB_SUPPLIER_CATEGORIES',
                'managed': True,
            },
        ),
    ]
