# Generated by Django 5.2 on 2025-04-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='formsubmission',
            table='inventory.FormSubmission',
        ),
    ]
