# Generated by Django 5.2 on 2025-06-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_tb_inventory_categories_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hanoi_inventory_categories',
            table='inventory"."HANOI_INVENTORY_CATEGORIES',
        ),
        migrations.AlterModelTable(
            name='la_inventory_categories',
            table='inventory"."LA_INVENTORY_CATEGORIES',
        ),
        migrations.AlterModelTable(
            name='mientay_inventory_categories',
            table='inventory"."MIENTAY_INVENTORY_CATEGORIES',
        ),
        migrations.AlterModelTable(
            name='naman_inventory_categories',
            table='inventory"."NAMAN_INVENTORY_CATEGORIES',
        ),
        migrations.AlterModelTable(
            name='pa_inventory_categories',
            table='inventory"."PA_INVENTORY_CATEGORIES',
        ),
    ]
