# Generated by Django 5.2 on 2025-06-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_tb_client_categories_tb_supplier_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_client_categories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tb_supplier_categories',
            options={'managed': False},
        ),
    ]
