# Generated by Django 5.2 on 2025-06-17 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_view_inventory_report_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_INVENTORY_CATEGORIES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_hang', models.CharField(max_length=50)),
                ('ten_hang', models.TextField()),
                ('dvt', models.CharField(max_length=50)),
                ('sl_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('don_gia_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ma_kho_luu_tru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'LA_INVENTORY_CATEGORIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('pass_field', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'login_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PA_INVENTORY_CATEGORIES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_hang', models.CharField(max_length=50)),
                ('ten_hang', models.TextField()),
                ('dvt', models.CharField(max_length=50)),
                ('sl_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('don_gia_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ma_kho_luu_tru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'PA_INVENTORY_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('subsidiary', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventory"."user_permissions',
                'managed': True,
            },
        ),
    ]
