# Generated by Django 5.2 on 2025-06-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_hanoi_inventory_categories_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
