# Generated by Django 5.2 on 2025-06-24 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_delete_formsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_INVENTORY_STOCK_RECEIVED_ISSSUED_RETURNED',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('so_phieu', models.CharField(max_length=50)),
                ('phan_loai_nhap_xuat_hoan', models.CharField(max_length=50)),
                ('ma_doi_tuong', models.CharField(max_length=50)),
                ('ngay_tren_phieu', models.DateTimeField()),
                ('so_phieu_de_nghi', models.CharField(max_length=50)),
                ('thong_tin_them', models.TextField(blank=True, null=True)),
                ('stt_dong', models.IntegerField(blank=True, null=True)),
                ('ma_hang', models.CharField(max_length=50)),
                ('so_luong', models.DecimalField(decimal_places=2, max_digits=15)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ghi_chu_sp', models.TextField(blank=True, null=True)),
                ('ma_kho_nhan', models.CharField(max_length=50)),
                ('ma_kho_xuat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventory"."LA_INVENTORY_STOCK_RECEIVED_ISSSUED_RETURNED',
                'managed': True,
            },
        ),
    ]
