# Generated by Django 5.2 on 2025-06-17 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_la_inventory_categories_logininfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HANOI_INVENTORY_CATEGORIES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_hang', models.CharField(max_length=50)),
                ('ten_hang', models.TextField()),
                ('dvt', models.CharField(max_length=50)),
                ('sl_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('don_gia_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ma_kho_luu_tru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'HANOI_INVENTORY_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MIENTAY_INVENTORY_CATEGORIES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_hang', models.CharField(max_length=50)),
                ('ten_hang', models.TextField()),
                ('dvt', models.CharField(max_length=50)),
                ('sl_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('don_gia_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ma_kho_luu_tru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'MIENTAY_INVENTORY_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NAMAN_INVENTORY_CATEGORIES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(max_length=10)),
                ('xoa_sua', models.CharField(max_length=10)),
                ('ma_hang', models.CharField(max_length=50)),
                ('ten_hang', models.TextField()),
                ('dvt', models.CharField(max_length=50)),
                ('sl_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('don_gia_ton_dau_ky', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ma_kho_luu_tru', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'NAMAN_INVENTORY_CATEGORIES',
                'managed': True,
            },
        ),
    ]
