# Generated by Django 5.2 on 2025-06-24 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_la_inventory_stock_received_isssued_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='LA_SUPPLIER_CATEGORIES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.CharField(default='', max_length=10)),
                ('xoa_sua', models.CharField(default='', max_length=10)),
                ('ma_nha_cung_cap', models.CharField(default='', max_length=50)),
                ('ten_nha_cung_cap', models.TextField(default='')),
                ('ma_phan_loai_01', models.CharField(default='', max_length=50)),
                ('ma_phan_loai_02', models.CharField(default='', max_length=50)),
                ('ma_phan_loai_03', models.CharField(default='', max_length=50)),
                ('ma_phan_loai_04', models.CharField(default='', max_length=50)),
                ('ma_phan_loai_05', models.CharField(default='', max_length=50)),
                ('ma_phan_loai_06', models.CharField(default='', max_length=50)),
                ('ma_phan_loai_07', models.CharField(default='', max_length=50)),
                ('ma_phan_loai_08', models.CharField(default='', max_length=50)),
                ('mst', models.CharField(default='', max_length=20)),
                ('dia_chi', models.TextField(default='')),
            ],
            options={
                'db_table': 'inventory"."LA_SUPPLIER_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='dia_chi',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='id_nhan_vien',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_nha_cung_cap',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_01',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_02',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_03',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_04',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_05',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_06',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_07',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ma_phan_loai_08',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='mst',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='ten_nha_cung_cap',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tb_supplier_categories',
            name='xoa_sua',
            field=models.CharField(default='', max_length=10),
        ),
    ]
