# Generated by Django 5.2 on 2025-06-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_hanoi_inventory_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanoi_inventory_categories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mientay_inventory_categories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='naman_inventory_categories',
            options={'managed': False},
        ),
    ]
